format: 0.2

preset:
  name: node_js
  node_js: 10

cloud:
  type: sandbox
  owner: SHRI_DEPLOY

container:
  type: LXC
  storage: sandbox-resource
  resource:
    owner: TRENDBOX_CI_TEAM
    attrs:
      released: stable
      components: base,docker,node_js

env:
  SANDBOX_PRIVILEGED_CONTAINER: 1
  PROJECT: trenders
  TAG: master
  DOCKER_REGISTRY_PATH: registry.yandex.net/shri

lifecycle:
  script:
  - |
    if [[ "$TRENDBOX_BRANCH" != 'master' ]]; then
      echo "CI для мастера"
      exit 0
    fi
    echo "Cloning source code..."
    cat <<< "$SSH_PRIVATE_KEY" > id_rsa
    chmod 400 id_rsa
    ssh-add id_rsa
    git clone ssh://git@bb.yandex-team.ru/SHRI-2019/"$PROJECT".git sources
    cd sources
    git checkout "$TRENDBOX_BRANCH"
    echo "Preparing environment..."
    sudo service docker start
    docker login -u "$DOCKER_USER" -p "$DOCKER_TOKEN" registry.yandex.net
    curl "https://bootstrap.pypa.io/get-pip.py" -o "get-pip.py"
    python get-pip.py
    pip install -i https://pypi.yandex-team.ru/simple/ citclient
    cd ./client
    echo "Installing dependencies..."
    npm ci
    echo "Building bundle..."
    npm run build || exit 1
    echo "Building docker image..."
    cd ../
    docker build --network=host -t "$DOCKER_REGISTRY_PATH/$PROJECT:$TAG" ./client
    echo "Pushing docker image..."
    docker push "$DOCKER_REGISTRY_PATH/$PROJECT:$TAG"
    echo "Deploying new container..."
    citclient --custom-context '{"DOCKER":{"tag":"'$TAG'","registry_path":"'$DOCKER_REGISTRY_PATH'/'$PROJECT'", "project": "'$PROJECT'"}}' qloud.deploy --sync
    sudo service docker stop

